version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC

  api:
    build:
      context: ./backend
      dockerfile: Plataforma.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./backend/data:/app/data
    ports:
      - "5000:8080"
    depends_on:
      - jaeger

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://localhost:5000"
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  api_data: {}
